title: THINGS GAME
logo: pics/materials/Screenshot 2024-10-10 at 23.58.49.png
theme: jekyll-theme-cayman
# Add your navigation links here
navigation:
  - title: Home
    url: /
  - title: How to Play
    url: /game_rules.html/  
  - title: How to Make
    url: /hands_on.html/  #



